## Numpy

In [3]:
import numpy as np

In [4]:
np.__version__

'1.25.2'

In [5]:
m1=np.array([2,4,6,8,10])
m2=np.array([1,3,5,7,9])

In [6]:
m1+m2

array([ 3,  7, 11, 15, 19])

In [7]:
m1*m2

array([ 2, 12, 30, 56, 90])

In [11]:
mx=m1

In [8]:
m3=np.random.randn(10,10)

In [9]:
m3

array([[ 1.82393379, -1.2597521 , -0.01064171, -0.12758173,  1.21940385,
        -1.26556439,  1.03693414, -0.86372746,  1.26123541,  1.34981005],
       [ 0.94510778,  1.46183299,  0.59522802,  0.68174207,  0.5300078 ,
        -1.05261242, -0.9016581 , -0.94635019, -0.34487354,  0.60058486],
       [-1.09795899, -0.65908795, -0.64136165, -0.5347218 ,  0.1201725 ,
        -0.96606287,  1.38183257, -0.91293958, -0.50656772, -0.54519709],
       [-0.99818632, -1.35536706, -0.51413313, -0.39844083,  1.96047167,
        -1.11943235, -1.03064153, -2.85753887,  1.01957184,  0.49283843],
       [-0.79744419, -0.54114333,  0.83435232,  0.4320979 , -0.71800597,
         1.91934419, -1.13061954,  0.16241838,  0.57824004,  2.59843714],
       [ 0.0634514 , -1.08902501,  1.76369405, -0.30358973, -0.22514482,
         1.0913796 ,  0.57792874, -0.23516302,  1.14174273, -0.67869539],
       [ 0.51288504,  1.77676954, -0.08199508,  1.33445242,  0.61199521,
         0.1870112 , -0.0771417 , -1.56703057

In [12]:
m4 = mx*3

In [13]:
m4

array([ 6, 12, 18, 24, 30])

In [14]:
m5=np.array([[1,2,3],[5,6,7],[9,10,11]])

In [15]:
m5

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [16]:
m5.shape

(3, 3)

In [17]:
m6=np.zeros(50)
m6

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
m7=np.ones(50)
m7

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])